services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production # Carga las variables desde este archivo
    # Las variables de entorno definidas aquí abajo (environment) 
    # pueden sobreescribir las del env_file si tienen el mismo nombre,
    # o puedes quitarlas si ya están todas en .env.production.
    # Por ahora, las comentaré para priorizar .env.production.
    # environment:
    #   NODE_ENV: production 
    #   DATABASE_URL: "postgres://admin:Lumar5998@lumarapp.marceloremeseiro.com:55002/lumar"
    #   JWT_SECRET: supersecreto123456789
    ports:
      - "1011:1011"  # Asegurarse que sea 1011:1011 para coincidir con el Dockerfile
    volumes:
      # Bind mount simple: mapea el directorio local ./public/uploads al directorio del contenedor
      - ./public/uploads:/app/public/uploads  
    # depends_on ya no es necesario porque la BD es externa
    # Crear el directorio localmente si no existe
    init: true # Usar init system para manejar la terminación correcta de procesos
    restart: unless-stopped # Reiniciar el contenedor a menos que sea detenido manualmente

# No necesitamos definir volúmenes nombrados explícitamente aquí
# volumes:
#   uploads:
#     driver: local

# El volumen db_data ya no es necesario
# volumes:
#   db_data: 